import type { ReactNode } from 'react';

/**
 * AI provenance marker — the small pill wearing the conic rainbow rim.
 *
 * Says "a model wrote this", and it is the ONLY thing that says it. The rim
 * used to be worn by the whole insight card as well (`.insight-rim`), which
 * meant a 400px surface was spending the app's loudest visual device on
 * provenance — a footnote at the size of a headline, competing with the
 * sentence it was annotating. The card is now an ordinary `.glass-card` and the
 * badge carries the marking alone, which is the job a badge is for.
 *
 * Lifted out of `StatusBadge` when that happened. It had been `variant="ai"`
 * there, but it never fitted: the other three variants are pure style objects
 * differing in colour and padding, while this one early-returned with its own
 * DOM, no border, and a CSS class. It is also not a STATUS — Live / Coming soon
 * / Refine all describe the state of a thing, and this describes where the text
 * came from. Same shape, different question.
 *
 * The ring is a masked `::before` on `.badge-ai` (globals.css) rather than a
 * border, because a conic gradient cannot be a border-color. That is also why
 * the label sits in its own positioned span: the ::before paints above the
 * parent's text, so the label has to be lifted onto its own layer to stay
 * readable. Do not "simplify" either away.
 */
export interface AIBadgeProps {
  /** Usually the word "AI" — kept as children so it can be translated. */
  children: ReactNode;
  /** Accessible description, e.g. "Generated by AI". Omit if the surrounding text already says so. */
  label?: string;
}

export default function AIBadge({ children, label }: AIBadgeProps) {
  return (
    <span
      className="badge-ai"
      aria-label={label}
      title={label}
      style={{
        display: 'inline-block',
        borderRadius: 'var(--radius-pill)',
        whiteSpace: 'nowrap',
        fontWeight: 600,
        letterSpacing: '0.04em',
        textTransform: 'uppercase',
        fontSize: 'var(--fs-2xs)',
        padding: '3px 9px',
        color: 'var(--text-primary)',
      }}
    >
      <span style={{ position: 'relative' }}>{children}</span>
    </span>
  );
}
